apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm-deploy-role
rules:
- apiGroups: ["", "apps", "extensions", "batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-deploy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helm-deploy-role
subjects:
- kind: ServiceAccount
  name: helm-deploy
